name: school_teacher_app
description: A new Flutter project for the School Teacher App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  lucide_icons_flutter: ^3.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
